#include "stdafx.h"
#include "constants.h"

int GetConstantValue(named_constant *list, const char *name) {
	named_constant *p;
	for(p = list; p->name != NULL; p++) {
		if(stricmp(p->name, name) == 0) {
			return p->value;
		}
	}
	return 0;
}

CONSTANT_START(MSHTML)
	CONSTANT(IDM_UNKNOWN)
	CONSTANT(IDM_ALIGNBOTTOM)
	CONSTANT(IDM_ALIGNHORIZONTALCENTERS)
	CONSTANT(IDM_ALIGNLEFT)
	CONSTANT(IDM_ALIGNRIGHT)
	CONSTANT(IDM_ALIGNTOGRID)
	CONSTANT(IDM_ALIGNTOP)
	CONSTANT(IDM_ALIGNVERTICALCENTERS)
	CONSTANT(IDM_ARRANGEBOTTOM)
	CONSTANT(IDM_ARRANGERIGHT)
	CONSTANT(IDM_BRINGFORWARD)
	CONSTANT(IDM_BRINGTOFRONT)
	CONSTANT(IDM_CENTERHORIZONTALLY)
	CONSTANT(IDM_CENTERVERTICALLY)
	CONSTANT(IDM_CODE)
	CONSTANT(IDM_DELETE)
	CONSTANT(IDM_FONTNAME)
	CONSTANT(IDM_FONTSIZE)
	CONSTANT(IDM_GROUP)
	CONSTANT(IDM_HORIZSPACECONCATENATE)
	CONSTANT(IDM_HORIZSPACEDECREASE)
	CONSTANT(IDM_HORIZSPACEINCREASE)
	CONSTANT(IDM_HORIZSPACEMAKEEQUAL)
	CONSTANT(IDM_INSERTOBJECT)
	CONSTANT(IDM_MULTILEVELREDO)
	CONSTANT(IDM_SENDBACKWARD)
	CONSTANT(IDM_SENDTOBACK)
	CONSTANT(IDM_SHOWTABLE)
	CONSTANT(IDM_SIZETOCONTROL)
	CONSTANT(IDM_SIZETOCONTROLHEIGHT)
	CONSTANT(IDM_SIZETOCONTROLWIDTH)
	CONSTANT(IDM_SIZETOFIT)
	CONSTANT(IDM_SIZETOGRID)
	CONSTANT(IDM_SNAPTOGRID)
	CONSTANT(IDM_TABORDER)
	CONSTANT(IDM_TOOLBOX)
	CONSTANT(IDM_MULTILEVELUNDO)
	CONSTANT(IDM_UNGROUP)
	CONSTANT(IDM_VERTSPACECONCATENATE)
	CONSTANT(IDM_VERTSPACEDECREASE)
	CONSTANT(IDM_VERTSPACEINCREASE)
	CONSTANT(IDM_VERTSPACEMAKEEQUAL)
	CONSTANT(IDM_JUSTIFYFULL)
	CONSTANT(IDM_BACKCOLOR)
	CONSTANT(IDM_BOLD)
	CONSTANT(IDM_BORDERCOLOR)
	CONSTANT(IDM_FLAT)
	CONSTANT(IDM_FORECOLOR)
	CONSTANT(IDM_ITALIC)
	CONSTANT(IDM_JUSTIFYCENTER)
	CONSTANT(IDM_JUSTIFYGENERAL)
	CONSTANT(IDM_JUSTIFYLEFT)
	CONSTANT(IDM_JUSTIFYRIGHT)
	CONSTANT(IDM_RAISED)
	CONSTANT(IDM_SUNKEN)
	CONSTANT(IDM_UNDERLINE)
	CONSTANT(IDM_CHISELED)
	CONSTANT(IDM_ETCHED)
	CONSTANT(IDM_SHADOWED)
	CONSTANT(IDM_FIND)
	CONSTANT(IDM_SHOWGRID)
	CONSTANT(IDM_OBJECTVERBLIST0)
	CONSTANT(IDM_OBJECTVERBLIST1)
	CONSTANT(IDM_OBJECTVERBLIST2)
	CONSTANT(IDM_OBJECTVERBLIST3)
	CONSTANT(IDM_OBJECTVERBLIST4)
	CONSTANT(IDM_OBJECTVERBLIST5)
	CONSTANT(IDM_OBJECTVERBLIST6)
	CONSTANT(IDM_OBJECTVERBLIST7)
	CONSTANT(IDM_OBJECTVERBLIST8)
	CONSTANT(IDM_OBJECTVERBLIST9)
	CONSTANT(IDM_OBJECTVERBLISTLAST)
	CONSTANT(IDM_CONVERTOBJECT)
	CONSTANT(IDM_CUSTOMCONTROL)
	CONSTANT(IDM_CUSTOMIZEITEM)
	CONSTANT(IDM_RENAME)
	CONSTANT(IDM_IMPORT)
	CONSTANT(IDM_NEWPAGE)
	CONSTANT(IDM_MOVE)
	CONSTANT(IDM_CANCEL)
	CONSTANT(IDM_FONT)
	CONSTANT(IDM_STRIKETHROUGH)
	CONSTANT(IDM_DELETEWORD)
	CONSTANT(IDM_EXECPRINT)
	CONSTANT(IDM_JUSTIFYNONE)
	CONSTANT(IDM_TRISTATEBOLD)
	CONSTANT(IDM_TRISTATEITALIC)
	CONSTANT(IDM_TRISTATEUNDERLINE)

	CONSTANT(IDM_FOLLOW_ANCHOR)

	CONSTANT(IDM_INSINPUTIMAGE)
	CONSTANT(IDM_INSINPUTBUTTON)
	CONSTANT(IDM_INSINPUTRESET)
	CONSTANT(IDM_INSINPUTSUBMIT)
	CONSTANT(IDM_INSINPUTUPLOAD)
	CONSTANT(IDM_INSFIELDSET)

	CONSTANT(IDM_PASTEINSERT)
	CONSTANT(IDM_REPLACE)
	CONSTANT(IDM_EDITSOURCE)
	CONSTANT(IDM_BOOKMARK)
	CONSTANT(IDM_HYPERLINK)
	CONSTANT(IDM_UNLINK)
	CONSTANT(IDM_BROWSEMODE)
	CONSTANT(IDM_EDITMODE)
	CONSTANT(IDM_UNBOOKMARK)

	CONSTANT(IDM_TOOLBARS)
	CONSTANT(IDM_STATUSBAR)
	CONSTANT(IDM_FORMATMARK)
	CONSTANT(IDM_TEXTONLY)
	CONSTANT(IDM_OPTIONS)
	CONSTANT(IDM_FOLLOWLINKC)
	CONSTANT(IDM_FOLLOWLINKN)
	CONSTANT(IDM_VIEWSOURCE)
	CONSTANT(IDM_ZOOMPOPUP)

	// IDM_BASELINEFONT1, IDM_BASELINEFONT2, IDM_BASELINEFONT3, IDM_BASELINEFONT4,
	// and IDM_BASELINEFONT5 should be consecutive integers;
	//
	CONSTANT(IDM_BASELINEFONT1)
	CONSTANT(IDM_BASELINEFONT2)
	CONSTANT(IDM_BASELINEFONT3)
	CONSTANT(IDM_BASELINEFONT4)
	CONSTANT(IDM_BASELINEFONT5)

	CONSTANT(IDM_HORIZONTALLINE)
	CONSTANT(IDM_LINEBREAKNORMAL)
	CONSTANT(IDM_LINEBREAKLEFT)
	CONSTANT(IDM_LINEBREAKRIGHT)
	CONSTANT(IDM_LINEBREAKBOTH)
	CONSTANT(IDM_NONBREAK)
	CONSTANT(IDM_SPECIALCHAR)
	CONSTANT(IDM_HTMLSOURCE)
	CONSTANT(IDM_IFRAME)
	CONSTANT(IDM_HTMLCONTAIN)
	CONSTANT(IDM_TEXTBOX)
	CONSTANT(IDM_TEXTAREA)
	CONSTANT(IDM_CHECKBOX)
	CONSTANT(IDM_RADIOBUTTON)
	CONSTANT(IDM_DROPDOWNBOX)
	CONSTANT(IDM_LISTBOX)
	CONSTANT(IDM_BUTTON)
	CONSTANT(IDM_IMAGE)
	CONSTANT(IDM_OBJECT)
	CONSTANT(IDM_1D)
	CONSTANT(IDM_IMAGEMAP)
	CONSTANT(IDM_FILE)
	CONSTANT(IDM_COMMENT)
	CONSTANT(IDM_SCRIPT)
	CONSTANT(IDM_JAVAAPPLET)
	CONSTANT(IDM_PLUGIN)
	CONSTANT(IDM_PAGEBREAK)
	CONSTANT(IDM_HTMLAREA)

	CONSTANT(IDM_PARAGRAPH)
	CONSTANT(IDM_FORM)
	CONSTANT(IDM_MARQUEE)
	CONSTANT(IDM_LIST)
	CONSTANT(IDM_ORDERLIST)
	CONSTANT(IDM_UNORDERLIST)
	CONSTANT(IDM_INDENT)
	CONSTANT(IDM_OUTDENT)
	CONSTANT(IDM_PREFORMATTED)
	CONSTANT(IDM_ADDRESS)
	CONSTANT(IDM_BLINK)
	CONSTANT(IDM_DIV)

	CONSTANT(IDM_TABLEINSERT)
	CONSTANT(IDM_RCINSERT)
	CONSTANT(IDM_CELLINSERT)
	CONSTANT(IDM_CAPTIONINSERT)
	CONSTANT(IDM_CELLMERGE)
	CONSTANT(IDM_CELLSPLIT)
	CONSTANT(IDM_CELLSELECT)
	CONSTANT(IDM_ROWSELECT)
	CONSTANT(IDM_COLUMNSELECT)
	CONSTANT(IDM_TABLESELECT)
	CONSTANT(IDM_TABLEPROPERTIES)
	CONSTANT(IDM_CELLPROPERTIES)
	CONSTANT(IDM_ROWINSERT)
	CONSTANT(IDM_COLUMNINSERT)

	CONSTANT(IDM_HELP_CONTENT)
	CONSTANT(IDM_HELP_ABOUT)
	CONSTANT(IDM_HELP_README)

	CONSTANT(IDM_REMOVEFORMAT)
	CONSTANT(IDM_PAGEINFO)
	CONSTANT(IDM_TELETYPE)
	CONSTANT(IDM_GETBLOCKFMTS)
	CONSTANT(IDM_BLOCKFMT)
	CONSTANT(IDM_SHOWHIDE_CODE)
	CONSTANT(IDM_TABLE)

	CONSTANT(IDM_COPYFORMAT)
	CONSTANT(IDM_PASTEFORMAT)
	CONSTANT(IDM_GOTO)

	CONSTANT(IDM_CHANGEFONT)
	CONSTANT(IDM_CHANGEFONTSIZE)
	CONSTANT(IDM_CHANGECASE)
	CONSTANT(IDM_SHOWSPECIALCHAR)

	CONSTANT(IDM_SUBSCRIPT)
	CONSTANT(IDM_SUPERSCRIPT)

	CONSTANT(IDM_CENTERALIGNPARA)
	CONSTANT(IDM_LEFTALIGNPARA)
	CONSTANT(IDM_RIGHTALIGNPARA)
	CONSTANT(IDM_REMOVEPARAFORMAT)
	CONSTANT(IDM_APPLYNORMAL)
	CONSTANT(IDM_APPLYHEADING1)
	CONSTANT(IDM_APPLYHEADING2)
	CONSTANT(IDM_APPLYHEADING3)

	CONSTANT(IDM_DOCPROPERTIES)
	CONSTANT(IDM_ADDFAVORITES)
	CONSTANT(IDM_COPYSHORTCUT)
	CONSTANT(IDM_SAVEBACKGROUND)
	CONSTANT(IDM_SETWALLPAPER)
	CONSTANT(IDM_COPYBACKGROUND)
	CONSTANT(IDM_CREATESHORTCUT)
	CONSTANT(IDM_PAGE)
	CONSTANT(IDM_SAVETARGET)
	CONSTANT(IDM_SHOWPICTURE)
	CONSTANT(IDM_SAVEPICTURE)
	CONSTANT(IDM_DYNSRCPLAY)
	CONSTANT(IDM_DYNSRCSTOP)
	CONSTANT(IDM_PRINTTARGET)
	CONSTANT(IDM_IMGARTPLAY)
	CONSTANT(IDM_IMGARTSTOP)
	CONSTANT(IDM_IMGARTREWIND)
	CONSTANT(IDM_PRINTQUERYJOBSPENDING)
	CONSTANT(IDM_SETDESKTOPITEM)

	CONSTANT(IDM_CONTEXTMENU)
	CONSTANT(IDM_GOBACKWARD)
	CONSTANT(IDM_GOFORWARD)
	CONSTANT(IDM_PRESTOP)

	CONSTANT(IDM_MP_MYPICS)
	CONSTANT(IDM_MP_EMAILPICTURE)
	CONSTANT(IDM_MP_PRINTPICTURE)

	CONSTANT(IDM_CREATELINK)
	CONSTANT(IDM_COPYCONTENT)

	CONSTANT(IDM_LANGUAGE)
	 
	CONSTANT(IDM_GETPRINTTEMPLATE)
	CONSTANT(IDM_SETPRINTTEMPLATE)
	CONSTANT(IDM_TEMPLATE_PAGESETUP)

	CONSTANT(IDM_REFRESH)
	CONSTANT(IDM_STOPDOWNLOAD)

	CONSTANT(IDM_ENABLE_INTERACTION)

	CONSTANT(IDM_LAUNCHDEBUGGER)
	CONSTANT(IDM_BREAKATNEXT)

	CONSTANT(IDM_INSINPUTHIDDEN)
	CONSTANT(IDM_INSINPUTPASSWORD)

	CONSTANT(IDM_OVERWRITE)

	CONSTANT(IDM_PARSECOMPLETE)

	CONSTANT(IDM_HTMLEDITMODE)

	CONSTANT(IDM_REGISTRYREFRESH)
	CONSTANT(IDM_COMPOSESETTINGS)

	CONSTANT(IDM_SHOWALLTAGS)
	CONSTANT(IDM_SHOWALIGNEDSITETAGS)
	CONSTANT(IDM_SHOWSCRIPTTAGS)
	CONSTANT(IDM_SHOWSTYLETAGS)
	CONSTANT(IDM_SHOWCOMMENTTAGS)
	CONSTANT(IDM_SHOWAREATAGS)
	CONSTANT(IDM_SHOWUNKNOWNTAGS)
	CONSTANT(IDM_SHOWMISCTAGS)
	CONSTANT(IDM_SHOWZEROBORDERATDESIGNTIME)

	CONSTANT(IDM_AUTODETECT)

	CONSTANT(IDM_SCRIPTDEBUGGER)

	CONSTANT(IDM_GETBYTESDOWNLOADED)

	CONSTANT(IDM_NOACTIVATENORMALOLECONTROLS)
	CONSTANT(IDM_NOACTIVATEDESIGNTIMECONTROLS)
	CONSTANT(IDM_NOACTIVATEJAVAAPPLETS)
	CONSTANT(IDM_NOFIXUPURLSONPASTE)

	CONSTANT(IDM_EMPTYGLYPHTABLE)
	CONSTANT(IDM_ADDTOGLYPHTABLE)
	CONSTANT(IDM_REMOVEFROMGLYPHTABLE)
	CONSTANT(IDM_REPLACEGLYPHCONTENTS)

	CONSTANT(IDM_SHOWWBRTAGS)

	CONSTANT(IDM_PERSISTSTREAMSYNC)
	CONSTANT(IDM_SETDIRTY)

	CONSTANT(IDM_RUNURLSCRIPT)

	#ifdef IE5_ZOOM
	CONSTANT(IDM_ZOOMRATIO)
	CONSTANT(IDM_GETZOOMNUMERATOR)
	CONSTANT(IDM_GETZOOMDENOMINATOR)
	#endif  // IE5_ZOOM

	// COMMANDS FOR COMPLEX TEXT
	CONSTANT(IDM_DIRLTR)
	CONSTANT(IDM_DIRRTL)
	CONSTANT(IDM_BLOCKDIRLTR)
	CONSTANT(IDM_BLOCKDIRRTL)
	CONSTANT(IDM_INLINEDIRLTR)
	CONSTANT(IDM_INLINEDIRRTL)

	// SHDOCVW
	CONSTANT(IDM_ISTRUSTEDDLG)

	// MSHTMLED
	CONSTANT(IDM_INSERTSPAN)
	CONSTANT(IDM_LOCALIZEEDITOR)

	// XML MIMEVIEWER
	CONSTANT(IDM_SAVEPRETRANSFORMSOURCE)
	CONSTANT(IDM_VIEWPRETRANSFORMSOURCE)

	// Scrollbar context menu
	CONSTANT(IDM_SCROLL_HERE)
	CONSTANT(IDM_SCROLL_TOP)
	CONSTANT(IDM_SCROLL_BOTTOM)
	CONSTANT(IDM_SCROLL_PAGEUP)
	CONSTANT(IDM_SCROLL_PAGEDOWN)
	CONSTANT(IDM_SCROLL_UP)
	CONSTANT(IDM_SCROLL_DOWN)
	CONSTANT(IDM_SCROLL_LEFTEDGE)
	CONSTANT(IDM_SCROLL_RIGHTEDGE)
	CONSTANT(IDM_SCROLL_PAGELEFT)
	CONSTANT(IDM_SCROLL_PAGERIGHT)
	CONSTANT(IDM_SCROLL_LEFT)
	CONSTANT(IDM_SCROLL_RIGHT)

	// IE) Form Editing Commands
	CONSTANT(IDM_MULTIPLESELECTION)
	CONSTANT(IDM_2D_POSITION)
	CONSTANT(IDM_2D_ELEMENT)
	CONSTANT(IDM_1D_ELEMENT)
	CONSTANT(IDM_ABSOLUTE_POSITION)
	CONSTANT(IDM_LIVERESIZE)
	CONSTANT(IDM_ATOMICSELECTION)

	// Auto URL detection mode
	CONSTANT(IDM_AUTOURLDETECT_MODE)

	// Legacy IE50 compatible paste
	CONSTANT(IDM_IE50_PASTE)

	// ie50 paste mode
	CONSTANT(IDM_IE50_PASTE_MODE)

	//;begin_internal
	CONSTANT(IDM_GETIPRINT)
	//;end_internal

	// for disabling selection handles
	CONSTANT(IDM_DISABLE_EDITFOCUS_UI)

	// for visibility/display in design
	CONSTANT(IDM_RESPECTVISIBILITY_INDESIGN)

	// set css mode
	CONSTANT(IDM_CSSEDITING_LEVEL)

	// New outdent
	CONSTANT(IDM_UI_OUTDENT)

	// Printing Status
	CONSTANT(IDM_UPDATEPAGESTATUS)

	// IME Reconversion 
	CONSTANT(IDM_IME_ENABLE_RECONVERSION)

	CONSTANT(IDM_KEEPSELECTION)

	CONSTANT(IDM_UNLOADDOCUMENT)

	CONSTANT(IDM_OVERRIDE_CURSOR)

	CONSTANT(IDM_PEERHITTESTSAMEINEDIT)

	CONSTANT(IDM_TRUSTAPPCACHE)

	CONSTANT(IDM_BACKGROUNDIMAGECACHE)

	CONSTANT(IDM_DEFAULTBLOCK)

	CONSTANT(IDM_MIMECSET__FIRST__)
	CONSTANT(IDM_MIMECSET__LAST__)

	CONSTANT(IDM_MENUEXT_FIRST__)
	CONSTANT(IDM_MENUEXT_LAST__)
	CONSTANT(IDM_MENUEXT_COUNT)

	// Commands mapped from the standard set.  We should
	// consider deleting them from public header files.

	CONSTANT(IDM_OPEN)
	CONSTANT(IDM_NEW)
	CONSTANT(IDM_SAVE)
	CONSTANT(IDM_SAVEAS)
	CONSTANT(IDM_SAVECOPYAS)
	CONSTANT(IDM_PRINTPREVIEW)
	CONSTANT(IDM_SHOWPRINT)
	CONSTANT(IDM_SHOWPAGESETUP)
	CONSTANT(IDM_PRINT)
	CONSTANT(IDM_PAGESETUP)
	CONSTANT(IDM_SPELL)
	CONSTANT(IDM_PASTESPECIAL)
	CONSTANT(IDM_CLEARSELECTION)
	CONSTANT(IDM_PROPERTIES)
	CONSTANT(IDM_REDO)
	CONSTANT(IDM_UNDO)
	CONSTANT(IDM_SELECTALL)
	CONSTANT(IDM_ZOOMPERCENT)
	CONSTANT(IDM_GETZOOM)
	CONSTANT(IDM_STOP)
	CONSTANT(IDM_COPY)
	CONSTANT(IDM_CUT)
	CONSTANT(IDM_PASTE)

	// Defines for IDM_ZOOMPERCENT
	CONSTANT(CMD_ZOOM_PAGEWIDTH)
	CONSTANT(CMD_ZOOM_ONEPAGE)
	CONSTANT(CMD_ZOOM_TWOPAGES)
	CONSTANT(CMD_ZOOM_SELECTION)
	CONSTANT(CMD_ZOOM_FIT)

	// IDMs for CGID_EditStateCommands group 
	CONSTANT(IDM_CONTEXT) 
	CONSTANT(IDM_HWND)

	// Shdocvw Execs on CGID_DocHostCommandHandler
	CONSTANT(IDM_NEW_TOPLEVELWINDOW)

	//
	// Undo persistence comands
	//
	CONSTANT(IDM_PRESERVEUNDOALWAYS)
	CONSTANT(IDM_PERSISTDEFAULTVALUES)
	CONSTANT(IDM_PROTECTMETATAGS)

	CONSTANT(IDM_GETFRAMEZONE)

	//;begin_internal
	// <New in IE6>
	CONSTANT(IDM_FIRE_PRINTTEMPLATEUP)
	CONSTANT(IDM_FIRE_PRINTTEMPLATEDOWN)
	CONSTANT(IDM_SETPRINTHANDLES)

	// added for Wapache 
	CONSTANT(IDM_ABOUT)
	CONSTANT(IDM_EXIT)
	CONSTANT(IDM_CLOSE)
	CONSTANT(IDM_FOCUS)

CONSTANT_END(MSHTML);

static const char * const status_lines[RESPONSE_CODES] =
{
    "100 Continue",
    "101 Switching Protocols",
    "102 Processing",
#define LEVEL_200  3
    "200 OK",
    "201 Created",
    "202 Accepted",
    "203 Non-Authoritative Information",
    "204 No Content",
    "205 Reset Content",
    "206 Partial Content",
    "207 Multi-Status",
#define LEVEL_300 11
    "300 Multiple Choices",
    "301 Moved Permanently",
    "302 Found",
    "303 See Other",
    "304 Not Modified",
    "305 Use Proxy",
    "306 unused",
    "307 Temporary Redirect",
#define LEVEL_400 19
    "400 Bad Request",
    "401 Authorization Required",
    "402 Payment Required",
    "403 Forbidden",
    "404 Not Found",
    "405 Method Not Allowed",
    "406 Not Acceptable",
    "407 Proxy Authentication Required",
    "408 Request Time-out",
    "409 Conflict",
    "410 Gone",
    "411 Length Required",
    "412 Precondition Failed",
    "413 Request Entity Too Large",
    "414 Request-URI Too Large",
    "415 Unsupported Media Type",
    "416 Requested Range Not Satisfiable",
    "417 Expectation Failed",
    "418 unused",
    "419 unused",
    "420 unused",
    "421 unused",
    "422 Unprocessable Entity",
    "423 Locked",
    "424 Failed Dependency",
    /* This is a hack, but it is required for ap_index_of_response
     * to work with 426.
     */
    "425 No code",
    "426 Upgrade Required",
#define LEVEL_500 46
    "500 Internal Server Error",
    "501 Method Not Implemented",
    "502 Bad Gateway",
    "503 Service Temporarily Unavailable",
    "504 Gateway Time-out",
    "505 HTTP Version Not Supported",
    "506 Variant Also Negotiates",
    "507 Insufficient Storage",
    "508 unused",
    "509 unused",
    "510 Not Extended"
};
